"""create plants table

Revision ID: 607a46b91244
Revises: e2642028ec0f
Create Date: 2023-06-15 16:42:12.804305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607a46b91244'
down_revision = 'e2642028ec0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
